click(Location(37, 137))
type("k", Key.CTRL)
paste("dj zdr")
wait(0.5)
type(Key.ENTER)
paste("!play keshi beside you")
type(Key.ENTER)
wait(1)
paste("!play keshi b.y.s")
type(Key.ENTER)
wait(1)
paste("!play keshi less of you"+ Key.ENTER)
type(Key.ENTER)
wait(1)
paste("!play keshi skeletons")
type(Key.ENTER)
wait(1)
paste("!play keshi right here")
type(Key.ENTER)
wait(1)
paste("!play keshi angostura")
type(Key.ENTER)
wait(1)
paste("!play keshi drunk")
type(Key.ENTER)
wait(1)
paste("!play keshi touch")
type(Key.ENTER)
wait(1)
paste("!play keshi somebody")
type(Key.ENTER)
wait(1)
paste("!play keshi 2 soon")
type(Key.ENTER)
wait(1)
paste("!play keshi summer")
type(Key.ENTER)
wait(1)
paste("!play keshi always")
type(Key.ENTER)
wait(1)
paste("!play keshi limbo")
type(Key.ENTER)
wait(1)
paste("!play keshi get it")
type(Key.ENTER)
wait(1)
paste("!play keshi more")
type(Key.ENTER)
wait(1)
paste("!play keshi blue")
type(Key.ENTER)
wait(1)
paste("!play keshi talk")
type(Key.ENTER)
wait(1)
paste("!play keshi westside")
type(Key.ENTER)
wait(1)
paste("!play keshi onoffonoff")
type(Key.ENTER)
wait(1)
paste("!play keshi like i need u")
type(Key.ENTER)
wait(1)
paste("!play keshi us")
type(Key.ENTER)
wait(1)
paste("!play keshi bandaids")
type(Key.ENTER)
wait(1)
paste("!play keshi xoxosos")
type(Key.ENTER)
wait(1)
paste("!play casey luong maybe")
type(Key.ENTER)
wait(1)
paste("!play keshi milli")
type(Key.ENTER)
wait(1)
paste("!play keshi hell/heaven")
type(Key.ENTER)
wait(1)
paste("!play keshi understand")
type(Key.ENTER)
wait(1)
paste("!play keshi alright")
type(Key.ENTER)
wait(1)
paste("!play keshi just friends")
type(Key.ENTER)
wait(1)
paste("!play keshi as long as it takes you")
type(Key.ENTER)
wait(1)
paste("!play keshi over u")
type(Key.ENTER)
wait(1)
paste("!play keshi angel")
type(Key.ENTER)
wait(1)
paste("!play keshi gabriel")
type(Key.ENTER)
wait(1)
paste("!play keshi pillows")
type(Key.ENTER)
wait(1)
paste("!play keshi magnolia")
type(Key.ENTER)
wait(1)
paste("!play keshi war with heaven")
type(Key.ENTER)
wait(1)
paste("!play keshi i swear ill never leave again")
type(Key.ENTER)
wait(1)
paste("!play keshi say something")
type(Key.ENTER)
wait(1)
paste("!play keshi the reaper")
type(Key.ENTER)
wait(1)
paste("!play keshi if youre not the one for me who is")
type(Key.ENTER)
wait(1)
paste(unicd("!play keshi père"))
type(Key.ENTER)
wait(1)
paste("!play keshi atlas")
type(Key.ENTER)
wait(1)
paste("!play keshi call me ")
type(Key.ENTER)
wait(1)
paste("!play keshi goes to watse")
type(Key.ENTER)
wait(1)
paste("!play keshi they dont fly as high as they used to")
type(Key.ENTER)
wait(1)
paste("!play keshi good days")
type(Key.ENTER)
wait(1)
paste("!play keshi sociopath")
type(Key.ENTER)
wait(1)
paste("!play keshi it kills me")
type(Key.ENTER)
wait(1)
paste("!play keshi breathing")
type(Key.ENTER)
wait(1)
paste("!play keshi godsplan")
type(Key.ENTER)
wait(1)